namespace:
  name: test
 
image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  cpu: 50m
  memory: 256Mi

service:
  type: ClusterIP
  port: 8111

configMap:
  data: "version: alpine"